services:
  postgres:
    container_name: pontotri-db
    image: postgres:16
    restart: always
    shm_size: 1gb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/pg:/data/postgres
